### ISSUE TITLE
Hierarchy is ignored during import when using Id as parentId

### ISSUE THREAD

**Issue by abernhar** [sphereio/sphere-category-sync#58]
### Description

Given some category tree

category 1 
sub category 1.1
category 2

I do an category export using id. If i import it using Id I have no hierarchy like this.

category 1 
category 1.1
category 2

If I do an category export using externalId and I import it using externalId i get an error message, that there is no parentId

I have to do this steps to get a hierarchy.

1. Export with ID
2. Import with ID
3. Export with externalId
4. Import with externalId

### Expected Behavior
If I do an import with id or externalId the hierarchy shouldn't be ignored.
It should be possible to do only one import.

### Current Behavior
See description.

**Comment by junajan** [comment]
Hello @abernhar .. I tried both cases (importing categories with parentBy set to id and externalId) and it looks like there are these two problems:

1) When using `id` in the `parentBy` parameter - the importer not the API do not check whether the parent id exists. That means that when creating:
```json
{
    "assets": [],
    "externalId": "a",
    "lastMessageSequenceNumber": 1,
    "name": {
        "en": "testCategory1"
    },
    "parent": {
        "id": "36a52073-1065-4897-aad1-5b1671fc3cd1",
        "typeId": "category"
    },
    "slug": {
        "en": "testCategory1"
    },
    "version": 1
}
```

The category won't be saved with the parent link:
```json
{
  "id": "a9be8c78-e08e-4407-b013-2bf1db81b888",
  "version": 1,
  "name": {
    "en": "testCategory1"
  },
  "slug": {
    "en": "testCategory1"
  },
  "ancestors": [],
  "orderHint": "0.00001500027368221190582078",
  "createdAt": "2017-07-14T10:16:08.222Z",
  "lastModifiedAt": "2017-07-14T10:16:08.222Z",
  "externalId": "CCC",
  "assets": [],
  "lastMessageSequenceNumber": 1
}
```
This should be fixed in this PR https://github.com/sphereio/sphere-category-sync/pull/59 which adds a check for an existence of a parent category identified by id.

2) When using `externalId` as a `parentId` there can be a problem that categories are not sorted properly before importing (it should import parent before its children) so there can be used `--sort` parameter which will sort imported CSV to the correct order. This option will be turned on by default in the future according to this issue https://github.com/sphereio/sphere-category-sync/issues/56
